---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "busybox.fullName" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{ include "busybox.labels" .| nindent 4 }}
data:
  APP_NAME: {{ include "busybox.name" . }}
  APP_ENV: "prod"
...