---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "busybox.fullName" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{ include "busybox.labels" .| nindent 4 }}
subjects:
- kind: ServiceAccount
  name: "{{ .Values.serviceAccountName}}"
  namespace: "{{ .Values.namespace }}"
roleRef:
  kind: Role 
  name: {{ include "busybox.fullName" . }}
  apiGroup: rbac.authorization.k8s.io
...