---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace:  "{{ .Release.Namespace }}"
  name: {{ include "busybox.fullName" . }}
  labels:
    {{ include "busybox.labels" .| nindent 4 }}
rules:
- apiGroups: [""]
  resources: [""]
  verbs: [""]
...