---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "busybox.fullName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "busybox.labels" .| nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.image.port }}
  selector:
    {{ include "busybox.labels" .| nindent 4 }}
  type: "{{ .Values.service.type }}"
...